steps:

- name: 'gcr.io/cloud-builders/go'
  args: ['get', '-d', 'google.golang.org/appengine']
  env: ['GOPATH=/gopath']
  volumes:
  - name: 'go'
    path: '/gopath'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', "app/app.yaml"]
  env: ['GOPATH=/workspace']
  volumes:
  - name: 'go'
    path: '/gopath'
timeout: "1600s"